services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pwd
    volumes:
      - ./src/schema.sql:/docker-entrypoint-initdb.d/init-db.sql
      - data:/data/postgres

volumes:
  data:
